#!/usr/bin/env bash

[[ $1 ]] || exit 1

prevkey=""
arr[0]=""

while IFS=: read key value; do
    [[ $prevkey == $key ]] && arr[${#arr[@]}-1]="$value" || arr+=("$value")
    prevkey="$key"
done < <(sed -nr '/"name":|"url":/{s/ |"|,//g; p}' "$1")

for element in ${arr[@]}; do 
    [[ $element =~ ^(http|www) ]] && printf "(%s)\n" "$element" || printf "[%s]\n" "$element"
done 

# bash bkmrks2mkdn Bookmarks | sed -nr 'H; ${g; s/]\n/]/g; s.\).\) <br/>.g; p}' > bookmarks.md

