#!/bin/sh

T='abc'
BGs=$(seq 40 47)

HEADER="\n            "
for BG in $BGs; do
	HEADER="$HEADER     ${BG}m"
done
printf "%b\n" "$HEADER"

for FG in   'm'    '1m' '30m' '1;30m' '31m' '1;31m' \
          '32m' '1;32m' '33m' '1;33m' '34m' '1;34m' \
          '35m' '1;35m' '36m' '1;36m' '37m' '1;37m'
  do LINE=""
  for BG in $BGs
    do LINE="$LINE \033[$FG\033[${BG}m  $T  \033[0m"
  done
  printf "%6s %b %b\n" "$FG" "\033[$FG  $T " "$LINE"
done
echo
