#!/usr/bin/env bash

builtin set -e

_printf="/usr/bin/printf"
_mount="/bin/mount"
_umount="/bin/umount"
_chroot="/usr/sbin/chroot"

_shell="/bin/bash"
_root="/mnt/data/gentoo"

pinfo() {
    ${_printf} -- ":: %s\n" "$1"
}

perror() {
    ${_printf} -- "--> %s\n" "$1" >&2
    builtin exit 1
}

(( UID )) && perror "you need to be root to run this script"

pinfo "checking mountpoint"
[[ -e "${_root}" ]] || perror "mountpoint doesn't exist: ${_root}"

pinfo "mounting proc"
${_mount} -t proc none ${_root}/proc/
pinfo "mounting dev"
${_mount} --rbind /dev ${_root}/dev/

pinfo "chrooting into ${_root} .."
${_chroot} ${_root} ${_shell}

pinfo "unmounting dev"
${_umount} -l ${_root}/dev{/shm,/pts,}
pinfo "unmounting proc"
${_umount} -l ${_root}/proc

