#!/usr/bin/env bash
date="$(date +"%a %d/%m %R")"
vol="$(amixer get PCM | tail -1 | sed -r "s:.+\[(.+%)].+:\1:g")"
wifi="$(wireless_status)"
music="$(nowplaying)"
xsetroot -name "$music :: $wifi :: $vol :: $date"
