#!/usr/bin/env bash

# Convert any flash.flv to matroska.mkv
function flv2mkv() {
	ffmpeg -i "$1" -vcodec copy -sameq -acodec copy -f matroska ${f%.*}.mkv
}

# Convert any flash.flv to mp3
function flv2mp3() {
	ffmpeg -i "$1" -ab 320 -ar 44100 ${f%.*}.mp3
}

if [ -f "$1" ]
then
	case $1 in
	mp3)	flv2mp3 "$1" ;;
	mkv)	flv2mkv "$1" ;;
	esac
else
	echo "flvconv: error: $1 is not valid"
fi
