#!/usr/bin/env bash

name="shot.png"

function shot() {
    if $(which scrot &>/dev/null)
    then
        scrot -q100 "$name"
    elif $(which import &>/dev/null)
    then
        import -window root "$name"
    else
        echo "printscreen: no available method: abording" >&2
        exit 1
    fi
}

shot
exit 0
