#!/bin/sh

filename="${1:-capture.mkv}"
resolution="${2:-1920x1080}"

ffmpeg -f alsa -i plughw -acodec flac -f x11grab -r 30 -s "$resolution" -i "$DISPLAY" -vcodec libx264 -vpre lossless_ultrafast -threads 0 "$filename"

