#!/usr/bin/env bash

echo "$({ [[ -t 0 ]] \
    && curl -sF 'sprunge=<-' http://sprunge.us <"$1" \
    || curl -sF 'sprunge=<-' http://sprunge.us
}) $*" | tee -a /tmp/saved.urls | xargs echo -n | xclip -i && xclip -o && echo

