#!/usr/bin/env bash

function fsprunge() {
    curl -sF 'sprunge=<-' http://sprunge.us < $1 | xsel -i
    xsel -o 
}   

function isprunge() {
	curl -sF 'sprunge=<-' http://sprunge.us | xsel -i
	xsel -o
}

[[ -t 0 ]] && fsprunge $1 && exit 0
[[ -t 1 ]] && isprunge && exit 0

exit 1
