#!/usr/bin/env bash

[[ -t 0 ]]  && url="$(curl -sF 'sprunge=<-' http://sprunge.us <"$1")" \
            || url=$(curl -sF 'sprunge=<-' http://sprunge.us)
printf "txt: %s\t%s\n" "$url" "$*" | tee -a /tmp/saved.urls | xclip -i && xclip -o

