#!/usr/bin/env bash

mute="$(amixer get Master | sed -nr '$ s:.*\[(.+)]$:\1:p')"
vol="$(amixer get PCM | sed -nr '$ s:.*\[(.+%)].*:\1:p')"
{ [[ ${mute} == "off" ]] && vstat="ë"; } || \
{ (( ${vol%\%} <= 50  )) && vstat="ì"; } || vstat="í"

wifi="$(wireless_status)" wstat="¤"

music="$(mpc current)"
{ [[ -z "${music}" ]] && mstat="å"; } || \
{ mstat="$(mpc | sed -rn '2s/\[([[:alpha:]]+)].*/\1/p')"
  [[ "${mstat}" == "paused" ]] && mstat="ç" || mstat="ê"
}

date="$(date +"%a %d/%m %R")" dstat="¾"

    printf "\
^fg(#ff420e)%s ^fg(#579d1c)%s  \
^fg(#ff420e)%s ^fg(#579d1c)%s  \
^fg(#ff420e)%s ^fg(#579d1c)%s  \
^fg(#ff420e)%s ^fg(#579d1c)%s \n"     \
    "${mstat}" "${music:-[stopped]}"  \
    "${wstat}" "${wifi}"              \
    "${vstat}" "${vol}"               \
    "${dstat}" "${date}"

