#!/usr/bin/env bash

separator="\u19"

# volume
mute="$(amixer get Master | sed -nr '$ s:.*\[(.+)]$:\1:p')"
vol="$(amixer get PCM | sed -nr '$ s:.*\[(.+%)].*:\1:p')"
{ [[ ${mute} == "off" ]] && vstat="\uEB"; } || \
{ (( ${vol%\%} <= 20  )) && vstat="\uEC"; } || vstat="\uED"

wifi="$(wireless_status)" wstat="\uA4"

# now playing music
music="$(mpc current -f "%title% #&8by #&3%artist%")"
{ [[ -z "${music}" ]] && music="[stopped]" mstat="\uE5"; } || \
{ mstat="$(mpc | sed -rn '2s/\[([[:alpha:]]+)].*/\1/p')"
  [[ "${mstat}" == "paused" ]] && mstat="\uE7" || mstat="\uEA"
}

# date and time
date="$(date +"%a %d/%m %R")" dstat="\uC9"

# print it colored and formatted
printf "&8%b &4%b &3%s " \
    "${separator}" "${mstat}" "${music}" \
    "${separator}" "${wstat}" "${wifi}"  \
    "${separator}" "${vstat}" "${vol}"   \
    "${separator}" "${dstat}" "${date}"

