#!/usr/bin/env bash

mute="$(amixer get Master | sed -nr '$ s:.*\[(.+)]$:\1:p')"
vol="$(amixer get PCM | sed -nr '$ s:.*\[(.+%)].*:\1:p')"
{ [[ ${mute} == "off" ]] && vstat="ë"; } || \
{ (( ${vol%\%} <= 25  )) && vstat="ì"; } || vstat="í"

wifi="$(wireless_status)" wstat="¤"

music="$(mpc current)"
{ [[ -z "${music}" ]] && mstat="å"; } || \
{ mstat="$(mpc | sed -rn '2s/\[([[:alpha:]]+)].*/\1/p')"
  [[ "${mstat}" == "paused" ]] && mstat="ç" || mstat="ê"
}

date="$(date +"%a %d/%m %R")" dstat="¾"

printf "&5%s &3%s &5%s &3%s &5%s &3%s &5%s &3%s "         \
    "${mstat}" "${music:-[stopped]}" "${wstat}" "${wifi}" \
    "${vstat}" "${vol}" "${dstat}" "${date}"

