#!/bin/bash

mlog="$HOME/.lsyncd/music.sync.log"
plog="$HOME/.lsyncd/projects.sync.log"
slog="$HOME/.lsyncd/scripts.sync.log"

mdir="$HOME/music/"
pdir="$HOME/projects/"
sdir="$HOME/bin/"

smdir="/mnt/data/music/syncd_music/"
spdir="/mnt/data/projects/syncd/projects/"
ssdir="/mnt/data/projects/syncd/scripts/"

pkill -u "$USER" lsyncd
lsyncd -log scarce -logfile "$mlog" -rsync "$mdir" "$smdir" &
lsyncd -log scarce -logfile "$plog" -rsync "$pdir" "$spdir" &
lsyncd -log scarce -logfile "$slog" -rsync "$sdir" "$ssdir" &

