#!/usr/bin/env bash

diffvol="${1:-0}"
#current_vol="$(amixer get PCM | grep -o "\[[[:digit:]]\{1,3\}%\]" | tr -d "[]%" | head -1)"
current_vol="$(amixer get PCM | sed -n '/Left.*[0-9]\{1,3\}%/{s/.*\[\([0-9]\{1,3\}\)%\].*/\1/p;}')"
updated_vol="$(( $current_vol + $diffvol ))"
icon="notification-audio-volume-"

if [[ $1 = toggle ]] || [[ $1 = mute ]]
then
    amixer set Master toggle
else
    amixer set PCM ${updated_vol}%
fi

if [[ $1 = toggle ]] || [[ $1 = mute ]]
then icon+="muted"
elif (( $current_vol > 67 ))
then icon+="high"
elif (( $current_vol > 33 ))
then icon+="medium"
else icon+="low" #if (( display_volume > 0 )); then
fi

# uncomment to enable desktop notifications
#notify-send -i $icon -h int:value:$updated_vol -h string:synchronous:volume -t 1000 "${updated_vol}%"

