#!/usr/bin/env bash

diffvol="$1"
current_vol="$(amixer get PCM | grep -o "\[[[:digit:]]\{1,3\}%\]" | tr -d "[]%" | head -1)"

if [ "$1" = "toggle" ]
then
    amixer set Master toggle
else
    updated_vol="$(( $current_vol + $diffvol ))"
    amixer set PCM ${updated_vol}%
fi

icon="notification-audio-volume-"
if [ "$1" = "toggle" ]
then
  icon+="muted"
elif (( display_volume > 67 ))
then
  icon+="high"
elif (( display_volume > 33 ))
then 
  icon+="medium"
else #if (( display_volume > 0 )); then 
  icon+="low"
fi
notify-send -i $icon -h int:value:$updated_vol -h string:synchronous:volume -t 1000 "${updated_vol}%"

