#!/usr/bin/env bash

: "${wm:=monsterwm}"
: "${ff:="/tmp/${wm}.fifo"}"

while sleep 1; do statusbar
done | dzen2 -h 18 -w 1520 -x 400 -ta r -e -p -fn "-misc-terminusmod.icons-medium-r-normal--12-120-72-72-c-60-*-*" &

[[ -p $ff ]] || mkfifo -m 600 "$ff"
ds=("web" "dev" "foo")
ms=("[T]" "[M]" "[B]" "[G]" "[F]")
fn="-xos4-terminus-medium-r-normal--12-120-72-72-c-60-*-*"
while read -r; do
    [[ $REPLY =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]] && read -ra desktops <<< "$REPLY" || continue
    for desktop in "${desktops[@]}"; do
        IFS=':' read -r d w m c u <<< "$desktop"
        ((c)) && fg="#000" bg="#579d1c" i="${ms[$m]}" || fg="" bg=""
        ((u)) && fg="#000" bg="#ff420e"
        r+="^bg($bg)^fg($fg) ${ds[$d]} ${w/#0/∅} ^fg()^bg()"
    done
    printf "%s %s\n" "$r" "$i" && unset r
done < "$ff" | dzen2 -h 18 -w 400 -ta l -e -p -fn "$fn" &

while :; do "$wm" || break; done | tee -a "$ff"
