#!/usr/bin/env bash

: "${wm:=monsterwm}"
: "${ff:="/tmp/${wm}.fifo"}"

[[ -p $ff ]] || mkfifo -m 600 "$ff"
ds=("web" "dev" "foo" "null")
ms=("T" "M" "B" "G" "F")

while read -t 60 -r wmout || true; do
    if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        read -ra desks <<< "$wmout" && unset out
        for desk in "${desks[@]}"; do
            IFS=':' read -r d w m c u <<< "$desk"
            ((c)) && fg="&4" i="${ms[$m]}" || fg="&3"
            ((u)) && w+='&5!'
            printf -v o "${fg}%s %s &8%b " "${ds[$d]}" "${w/#0/-}" "\u19"
            out+=("$o")
        done
    fi
    printf -- " &L%s&R%s\n" "${out[@]}&5[&3$i&5]" "$(statusbar)"
done < "$ff" | some_sorta_bar &

$wm | tee -a "$ff"
